services:
  service:
    build:
      context: ./service/
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        HOST_USERNAME: ${HOST_USERNAME:-user}
        HOST_GROUPNAME: ${HOST_GROUPNAME:-group}
    environment:
      - DISPLAY=${DISPLAY}
    ports:
      - 8888:8888
    tty: true
    restart: unless-stopped
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./service/app:/app
      - ./service/data:/data
      - ./service/root/jupyter:/root/.jupyter
