name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-test-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build service test image
        run: |
          docker build \
            -f service/Dockerfile \
            -t local/service-test:ci \
            service
      - name: Save images for downstream jobs
        run: |
          docker save local/service-test:ci | gzip > service-test.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: test-images
          path: |
            service-test.tar.gz
  service-tests:
    runs-on: ubuntu-latest
    needs: build-test-images
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: test-images
      - name: Load images
        run: |
          gunzip -c service-test.tar.gz | docker load
      - name: Run service tests
        run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml run --rm service_test

