name: CI

on:
  push:
    branches: ["**"]
    paths:
      - "service/**"
      - "docker-compose.yml"
      - ".github/workflows/docker.yml"
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show Docker versions (debug)
        run: |
          docker version
          docker compose version

      - name: Build containers
        env:
          DOCKER_BUILDKIT: 1
          HOST_UID: "1000"
          HOST_GID: "1000"
          DISPLAY: ":1"
          HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
          HOST_GROUPNAME: ${{ secrets.HOST_GROUPNAME }}
        run: |
          docker compose build --pull

      # ----- Code style / lint -----
      - name: Black (format check)
        env:
          DOCKER_BUILDKIT: 1
          HOST_UID: "1000"
          HOST_GID: "1000"
          DISPLAY: ":1"
          HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
          HOST_GROUPNAME: ${{ secrets.HOST_GROUPNAME }}
        run: |
          docker compose run --rm \
            --entrypoint black service --check --diff .

      - name: Ruff (lint)
        env:
          DOCKER_BUILDKIT: 1
          HOST_UID: "1000"
          HOST_GID: "1000"
          DISPLAY: ":1"
          HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
          HOST_GROUPNAME: ${{ secrets.HOST_GROUPNAME }}
        run: |
          docker compose run --rm \
            -e RUFF_CACHE_DIR=/tmp/ruff_cache \
            -e XDG_CACHE_HOME=/tmp/xdg-cache \
            --entrypoint ruff service check .

      # ----- Tests -----
      - name: Pytest
        env:
          DOCKER_BUILDKIT: 1
          HOST_UID: "1000"
          HOST_GID: "1000"
          DISPLAY: ":1"
          HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
          HOST_GROUPNAME: ${{ secrets.HOST_GROUPNAME }}
        run: |
          docker compose run --rm \
            -e XDG_CACHE_HOME=/tmp/xdg-cache \
            --entrypoint sh service -lc 'mkdir -p /tmp/pytest_cache && pytest -q -o cache_dir=/tmp/pytest_cache'

      # ----- Closing -----
      - name: Cleanup
        env:
          DOCKER_BUILDKIT: 1
          HOST_UID: "1000"
          HOST_GID: "1000"
          DISPLAY: ":1"
          HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
          HOST_GROUPNAME: ${{ secrets.HOST_GROUPNAME }}
        if: always()
        run: |
          docker compose  down -v --remove-orphans
